project:
  type: website
  output-dir: docs

website:
  title: "Rokei Notes"

  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - sidebar:study
      - sidebar:research

  sidebar:
    - id: study
      title: "Study Notes"
      style: docked
      search: true
      collapse-level: 2
      contents:
        - study/index.qmd
        - section: "Math"
          href: study/math/index.qmd
          contents:
            - study/math/calculus.qmd
            - study/math/linear-algebra.qmd

    - id: research
      title: "Research Log"
      style: docked
      search: true
      collapse-level: 2
      contents:
        - research/index.qmd
        - section: "Paper Reviews"
          href: research/papers/index.qmd
          contents:
            - research/papers/paper-review-1.qmd
        - section: "Experiment Logs"
          href: research/logs/index.qmd
          contents:
            - research/logs/experiment-log-1.qmd

format:
  html:
    theme: morpy
    toc: true
    code-copy: true
    code-fold: true