project:
  type: website
  output-dir: docs
  preview:
    watch-inputs: true
    navigate: true
    browser: true

website:
  title: "Rokei Notes"
  plausible-analytics: |
    <!-- Privacy-friendly analytics by Plausible -->
    <script async src="https://plausible.io/js/pa-q1uQ7QEv5o9DOQFiYigvC.js"></script>
    <script>
      window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
      plausible.init()
    </script>

  site-url: "https://dreamian.github.io"
  site-path: "/"

  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Study Notes
        menu:
          - text: Math
            href: study/math/index.qmd
          - text: Algorithms
            href: study/algorithm/index.qmd
      - text: Research Log
        menu:
          - text: Paper Reviews
            href: research/papers/index.qmd
          - text: Experiment Logs
            href: research/logs/index.qmd

execute:
  python: C:\Users\dream\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe

format:
  html:
    theme: morpy
    toc: true
    code-copy: true
    code-fold: true