project:
  type: website
  output-dir: docs
  preview:
    watch-inputs: true
    navigate: true
    browser: true

website:
  title: "Rokei Notes"
  plausible-analytics: |
    <script async src="https://plausible.io/js/pa-XXXXXX.js"></script>
    <script>
      window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
      plausible.init()
    </script>

  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Study Notes
        menu:
          - text: Math
            href: study/math/index.qmd
          - text: Algorithms
            href: study/algorithm/index.qmd
      - text: Research Log
        menu:
          - text: Paper Reviews
            href: research/papers/index.qmd
          - text: Experiment Logs
            href: research/logs/index.qmd

format:
  html:
    theme: morpy
    toc: true
    code-copy: true
    code-fold: true