{
  "hash": "201fd05c0e29012c177d652625532d50",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"pandas 데이터프레임 처리 핵심 정리\"\nsubtitle: \"불리언 인덱싱 · apply · 문자열 처리 · explode · groupby/transform\"\ndate: \"2026-07-17\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: false\n    theme: cosmo\njupyter: python3\nexecute:\n  warning: false\n---\n\n::: {#cell-setup .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\n\nurl = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'\ndf_titanic = pd.read_csv(url)\ndf_titanic.head(3)\n```\n\n::: {#setup .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>PassengerId</th>\n      <th>Survived</th>\n      <th>Pclass</th>\n      <th>Name</th>\n      <th>Sex</th>\n      <th>Age</th>\n      <th>SibSp</th>\n      <th>Parch</th>\n      <th>Ticket</th>\n      <th>Fare</th>\n      <th>Cabin</th>\n      <th>Embarked</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>0</td>\n      <td>3</td>\n      <td>Braund, Mr. Owen Harris</td>\n      <td>male</td>\n      <td>22.0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>A/5 21171</td>\n      <td>7.2500</td>\n      <td>NaN</td>\n      <td>S</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>1</td>\n      <td>1</td>\n      <td>Cumings, Mrs. John Bradley (Florence Briggs Th...</td>\n      <td>female</td>\n      <td>38.0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>PC 17599</td>\n      <td>71.2833</td>\n      <td>C85</td>\n      <td>C</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>1</td>\n      <td>3</td>\n      <td>Heikkinen, Miss. Laina</td>\n      <td>female</td>\n      <td>26.0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>STON/O2. 3101282</td>\n      <td>7.9250</td>\n      <td>NaN</td>\n      <td>S</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n# 결측치 탐지와 불리언 인덱싱\n\n## `notna()` / `isna()`\n\n`notna()`는 각 원소가 결측(NaN)이 아니면 `True`, `isna()`는 그 반대인 **불리언 Series**를 반환한다.\n불리언 Series는 그 자체가 하나의 \"행 필터\"로 기능한다.\n\n::: {#6f7db32c .cell execution_count=2}\n``` {.python .cell-code}\ndf_titanic['Embarked'].isna().sum()   # True의 합 = 결측 개수\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nnp.int64(2)\n```\n:::\n:::\n\n\n## Series에서의 `.loc` — 인자 1개\n\nSeries는 1차원이므로 `.loc`에 행 선택자 하나만 들어간다.\n\n::: {#0b692515 .cell execution_count=3}\n``` {.python .cell-code}\nx = df_titanic['Embarked']\nx.loc[x.notna()].unique()             # 결측 제거 후 유일값\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n<StringArray>\n['S', 'C', 'Q']\nLength: 3, dtype: str\n```\n:::\n:::\n\n\n## DataFrame에서의 `.loc[행, 열]` — 인자 2개\n\nDataFrame은 2차원이므로 콤마로 **행 선택자와 열 선택자를 동시에** 지정한다.\n\n::: {#46c7fb2e .cell execution_count=4}\n``` {.python .cell-code}\ndf_titanic.loc[df_titanic['Cabin'].notna(), 'Cabin'].head()\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\n1      C85\n3     C123\n6      E46\n10      G6\n11    C103\nName: Cabin, dtype: str\n```\n:::\n:::\n\n\n열 선택자의 형태에 따라 반환 타입이 달라진다.\n\n| 열 선택자 | 예 | 반환 |\n|---|---|---|\n| 문자열 하나 | `.loc[cond, 'Cabin']` | Series |\n| 리스트 | `.loc[cond, ['Name', 'Sex']]` | DataFrame |\n| 라벨 슬라이스 | `.loc[cond, 'Pclass':'Cabin']` | DataFrame (**양 끝 포함**) |\n| 생략 또는 `:` | `.loc[cond]` | 모든 열 |\n\n::: {.callout-important}\n## 값 대입은 반드시 `.loc[행, 열] = 값`\n\n`df['col'][cond] = 값` 형태의 **연쇄 인덱싱(chained indexing)** 은 대입이\n복사본에 적용될 수 있어 원본이 바뀌지 않는 버그의 흔한 원인이다.\n한 번의 `.loc` 호출로 좌표를 지정하는 것이 표준 패턴이다.\n:::\n\n::: {#8e127bee .cell execution_count=5}\n``` {.python .cell-code}\ndf2 = df_titanic.copy()\ndf2.loc[df2['Embarked'].isna(), 'Embarked'] = df2['Embarked'].mode()[0]\ndf2['Embarked'].isna().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\nnp.int64(0)\n```\n:::\n:::\n\n\n복합 조건은 `&`, `|`로 결합하되 **각 조건을 괄호로 감싼다**\n(비교 연산자보다 `&`의 우선순위가 높기 때문).\n\n::: {#cf5e0455 .cell execution_count=6}\n``` {.python .cell-code}\ndf_titanic.loc[\n    (df_titanic['Sex'] == 'female') & (df_titanic['Pclass'] == 1),\n    'Survived'\n].mean()\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\nnp.float64(0.9680851063829787)\n```\n:::\n:::\n\n\n# `apply` — 열 단위 반복 연산\n\nDataFrame에 `apply(func)`를 쓰면 기본값 `axis=0`으로 **각 열이 Series로서\n함수에 차례로 전달**된다. for 루프로 열을 순회하는 것과 논리적으로 같지만,\n결과를 자동으로 하나의 객체로 모아 준다.\n\n::: {#7830b3ee .cell execution_count=7}\n``` {.python .cell-code}\ndf_titanic[['Survived', 'Pclass', 'Sex', 'Embarked']].apply(\n    lambda x: x.loc[x.notna()].unique().tolist()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\nSurvived            [0, 1]\nPclass           [3, 1, 2]\nSex         [male, female]\nEmbarked         [S, C, Q]\ndtype: object\n```\n:::\n:::\n\n\n함수가 스칼라를 반환하면 결과는 Series, 리스트 같은 객체를 반환하면\n\"값이 리스트인 Series\"가 된다.\n\n::: {.callout-tip}\n## `apply` + `pd.Series` = 한 열을 여러 열로\n\nSeries에 `apply`를 적용할 때 람다가 **`pd.Series`를 반환하면**, pandas가\n그 인덱스를 열 이름으로 삼아 결과를 **DataFrame으로 조립**해 준다.\n:::\n\n::: {#3dae2a59 .cell execution_count=8}\n``` {.python .cell-code}\ndf_titanic.loc[df_titanic['Cabin'].notna(), 'Cabin'].str.split(' ')\\\n    .explode()\\\n    .apply(\n        lambda x: pd.Series((x[:1], x[1:]), index=['Cabin_Type', 'Cabin_No'])\n    ).head()\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Cabin_Type</th>\n      <th>Cabin_No</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>C</td>\n      <td>85</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>C</td>\n      <td>123</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>E</td>\n      <td>46</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>G</td>\n      <td>6</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>C</td>\n      <td>103</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n`x[0]` 대신 `x[:1]`을 쓰면 빈 문자열에서 `IndexError` 없이 빈 문자열을\n반환하므로 슬라이싱이 더 방어적이다.\n\n벡터화된 대안이 있으면 그쪽이 간결하고 빠르다는 점도 기억해 둔다.\n\n::: {#6b6345ea .cell execution_count=9}\n``` {.python .cell-code}\n# apply 버전:  .apply(lambda x: x.isna().sum())\ndf_titanic[['Age', 'Cabin', 'Embarked']].isna().sum()   # 벡터화 버전\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\nAge         177\nCabin       687\nEmbarked      2\ndtype: int64\n```\n:::\n:::\n\n\n# `.str` 접근자 — 문자열 일괄 처리\n\n`.str`은 Series의 각 문자열 원소에 문자열 메서드를 벡터화하여 적용한다.\n`split` 결과(리스트의 Series)에서 원소를 꺼낼 때는 `.str[i]`를 이어 쓴다.\n\n::: {#1b8e146f .cell execution_count=10}\n``` {.python .cell-code}\n# \"성, 호칭. 이름\" 형식에서 호칭만 추출\ntitle = df_titanic['Name'].str.split(', ').str[1].str.split('.').str[0]\ntitle.value_counts().head()\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\nName\nMr        517\nMiss      182\nMrs       125\nMaster     40\nDr          7\nName: count, dtype: int64\n```\n:::\n:::\n\n\n::: {.callout-warning}\n## `.str.split` / `.str.rsplit`의 `n`은 키워드 전용 인자\n\n순수 파이썬 문자열은 `'A/5 21171'.rsplit(' ', 1)`처럼 위치 인자를 허용하지만,\npandas `.str` 접근자의 시그니처는 `rsplit(pat=None, *, n=-1, expand=False)`로\n`*` 뒤의 인자를 **키워드로만** 받는다.\n\n```python\ns.str.rsplit(' ', 1)     # TypeError!\ns.str.rsplit(' ', n=1)   # OK\n```\n\n에러 메시지의 \"3 were given\"은 `self`가 첫 위치 인자로 자동 전달되기 때문이다.\n`apply(lambda x: x.rsplit(' ', 1))`이 동작하는 이유는 람다 안의 `x`가\nSeries가 아닌 **개별 파이썬 문자열**이기 때문이다.\n:::\n\n`rsplit(' ', n=1)`은 오른쪽에서 한 번만 나누므로, 접두사에 공백이 있는\n`'STON/O 2. 3101282'` 같은 값에서도 마지막 조각(번호)이 보존된다.\n\n# `explode` — 관측 단위 재구성\n\n한 셀에 값 여러 개가 뭉쳐 있으면(\"C23 C25 C27\") 표준 집계 연산을 쓸 수 없다.\n`explode`는 **리스트의 각 원소를 독립된 행으로 펼쳐** \"한 셀 = 한 값\"을 만든다.\n\n::: {#dc304844 .cell execution_count=11}\n``` {.python .cell-code}\ncabin_exploded = df_titanic.loc[df_titanic['Cabin'].notna(), 'Cabin']\\\n    .str.split(' ')\\\n    .explode()\ncabin_exploded.loc[[27]]    # 인덱스 27: 객실 3개 → 행 3개\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\n27    C23\n27    C25\n27    C27\nName: Cabin, dtype: str\n```\n:::\n:::\n\n\n핵심 성질 두 가지:\n\n1. **인덱스가 복제**된다 — 펼쳐진 각 값이 어느 원래 행에서 나왔는지가 보존된다.\n2. 길이가 늘어난다 — 관측 단위가 \"승객\"에서 \"객실\"로 바뀐다.\n\n# `groupby` 심화\n\n## `level=0` — 인덱스로 그룹화\n\n`groupby`의 기준이 열이 아니라 **인덱스에 있을 때** `level` 인자를 쓴다.\n`level=0`은 인덱스의 첫 번째 층을 뜻하며, 단일 인덱스라면\n\"인덱스 그 자체로 묶어라\"가 된다. explode가 보존해 준 인덱스를\n그룹 키로 되살리는 전형적 조합이다.\n\n::: {#47282e6d .cell execution_count=12}\n``` {.python .cell-code}\ncabins_per_passenger = cabin_exploded.groupby(level=0).size()\ncabins_per_passenger.value_counts()   # 객실 개수별 승객 수\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```\nCabin\n1    180\n2     16\n3      6\n4      2\nName: count, dtype: int64\n```\n:::\n:::\n\n\n`size()`는 그룹의 **행 개수**, `count()`는 **결측이 아닌 값의 개수**를 센다.\n\n## `agg` vs `transform`\n\n같은 그룹 연산이지만 **결과를 돌려주는 방식**이 다르다.\n\n| | 계산 | 반환 형태 | 관측 단위 |\n|---|---|---|---|\n| `agg` (`median()` 등) | 그룹별 통계량 | **그룹 개수**만큼의 행 | 그룹 |\n| `transform` | 그룹별 통계량 | **원본과 같은 길이·인덱스** | 원래 행 |\n\n`transform`은 split → 그룹별 계산 → **broadcast**(각 행에 자기 그룹의 값을\n되돌려 뿌리기)의 3단계로 동작한다. 개념적으로는 조건부 통계량\n$E[Y \\mid \\text{그룹}]$을 각 관측치에 매핑하는 연산이다.\n\n::: {#5ae3ebdc .cell execution_count=13}\n``` {.python .cell-code}\ndf3 = df_titanic.copy()\n\n# 호칭별 나이 중앙값을 각 승객에게 대응시킨 891행 Series\nage_median_by_title = df3.groupby(title)['Age'].transform('median')\n\n# .loc 대입은 인덱스 정렬 기반 → 원본과 인덱스가 같아야 결측 위치에 정확히 들어간다\ndf3.loc[df3['Age'].isna(), 'Age'] = age_median_by_title\n\nprint(df3['Age'].isna().sum())\nprint(round(df_titanic['Age'].mean(), 3), '→', round(df3['Age'].mean(), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0\n29.699 → 29.39\n```\n:::\n:::\n\n\nagg 결과(인덱스가 호칭인 짧은 Series)를 우변에 넣으면 인덱스가 맞지 않아\n전부 NaN이 대입된다. `transform`이 필요한 이유는 이 **정렬 호환성**이다.\n\n전형적 용례: 그룹별 결측 대체, 그룹 내 표준화\n`(x - x.mean()) / x.std()`, 그룹 합 대비 비중 `x / x.sum()`.\n\n# 요약 치트시트\n\n| 하고 싶은 일 | 패턴 |\n|---|---|\n| 결측 아닌 행의 특정 열 | `df.loc[df['c'].notna(), 'c']` |\n| 결측 위치에 값 대입 | `df.loc[df['c'].isna(), 'c'] = 값` |\n| 열별 반복 연산 | `df[cols].apply(lambda x: ...)` |\n| 한 열 → 여러 열 | `s.apply(lambda x: pd.Series(..., index=[...]))` |\n| 문자열 나누고 원소 꺼내기 | `s.str.split(p).str[i]` |\n| 오른쪽에서 1회 분할 | `s.str.rsplit(' ', n=1)` (`n=` 필수) |\n| 한 셀의 여러 값 → 여러 행 | `s.str.split(' ').explode()` |\n| explode 후 원래 행 기준 집계 | `.groupby(level=0).size()` |\n| 그룹 통계량을 각 행에 붙이기 | `.groupby(k)['c'].transform('median')` |\n\n",
    "supporting": [
      "1_pandas_dataframe_notes_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}