{
  "hash": "cabe75d4ff1fccc859bda8bbad12605b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"유한 구간 MDP 연습문제 해답\"\nsubtitle: \"정책 평가, backward induction, Bellman 방정식 증명, 최적 정지 문제\"\ndate: \"2026-10-09\"\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n    code-fold: true\n    theme: cosmo\nexecute:\n  echo: false\n---\n\n# 문제 선정 {#sec-selection}\n\n유한 상태·유한 행동, Markov 정책, backward induction, Bellman 방정식 증명 범위에서 풀 수 있는 문제만 골랐다.\n\n| 문제 | 내용 | 다루는 개념 |\n|---|---|---|\n| 4.1 (Markov 버전) | 두 상태 모델에서 확률적 Markov 정책 평가 | 확률적 정책 평가 재귀, 최적값과 비교 |\n| 4.6 | 확률적 최단 경로 문제를 backward induction으로 풀기 | 비용 최소화, 전이확률 구성, 기대 보상 |\n| 4.21 | 두 프로젝트 bandit, 3기간 | backward induction, 동점과 복수 최적 정책 |\n| 4.25 | 최적 가치함수가 Bellman 방정식을 만족함을 ε 논법으로 증명 | 최적성 원리 (최적 정책 존재 가정 없이) |\n| 4.30, 4.31 | 콜·풋 옵션 행사 시점 | 최적 정지를 유한 구간 MDP로, 코딩으로 풀기 |\n\n**제외한 문제와 이유**\n\n| 문제 | 제외 이유 |\n|---|---|\n| 4.1 원문, 4.3, 4.18 | history-dependent 정책, ε-최적 정책 정리 일반형 |\n| 4.2 | 곱셈형 효용(위험 민감 목적) |\n| 4.4, 4.5, 4.7 | 연속 순차 배분, 최우추정 |\n| 4.8~4.10 | secretary problem |\n| 4.11~4.17, 4.19, 4.20, 4.24 | superadditivity, 단조 정책 |\n| 4.22, 4.23, 4.26~4.29, 4.32, 4.33 | 다른 장의 모델 설정에 의존하는 대형 응용 문제 |\n\n## 표기와 공통 도구 {#sec-tools}\n\n시점은 $t=0,1,\\dots,T$로 쓰고, 결정은 $t=0,\\dots,T-1$에서 한다. 원 문제의 decision epoch $1,\\dots,N$은 $t=0,\\dots,N-1$에 대응한다.\n\n$$\nQ^*_t(s,a):=r_t(s,a)+\\sum_{s'}p(s'\\mid s,a)\\,v^*_{t+1}(s'),\\qquad v^*_t(s)=\\max_a Q^*_t(s,a),\\qquad v^*_T=r_T\n$$\n\n확률적 Markov 정책의 평가:\n\n$$\nv^\\pi_t(s)=\\sum_a\\pi_t(a\\mid s)\\Big[r_t(s,a)+\\sum_{s'}p(s'\\mid s,a)\\,v^\\pi_{t+1}(s')\\Big],\\qquad v^\\pi_T=r_T\n$$\n\n비용 최소화 문제는 $\\max$를 $\\min$으로 바꾸면 된다.\n\n# 문제 4.1: 확률적 Markov 정책의 평가 {#sec-p41}\n\n::: {.callout-note}\n## 문제 (Markov 정책 버전으로 변형)\n다음 두 상태 모델에서 아래의 확률적 Markov 정책 $\\pi$의 기대 총보상을 계산하라. 원 문제는 history-dependent 확률적 정책을 평가하도록 하지만, 여기서는 Markov 정책으로 바꾸어 푼다.\n\n- $S=\\{s_1,s_2\\}$, $A_{s_1}=\\{a_{11},a_{12}\\}$, $A_{s_2}=\\{a_{21}\\}$, 결정 시점 2개($T=2$), $r_T\\equiv0$\n- $r(s_1,a_{11})=5$, $p(s_1\\mid s_1,a_{11})=p(s_2\\mid s_1,a_{11})=0.5$\n- $r(s_1,a_{12})=10$, $p(s_2\\mid s_1,a_{12})=1$\n- $r(s_2,a_{21})=-1$, $p(s_2\\mid s_2,a_{21})=1$\n- 정책: $\\pi_0(a_{11}\\mid s_1)=0.7$, $\\pi_0(a_{12}\\mid s_1)=0.3$, $\\pi_1(a_{11}\\mid s_1)=0.4$, $\\pi_1(a_{12}\\mid s_1)=0.6$, $s_2$에서는 항상 $a_{21}$\n:::\n\n## 정책 아래의 보상 벡터와 전이 행렬\n\n확률적 정책은 각 상태에서 행동 분포로 평균을 낸 보상과 전이확률을 만든다.\n\n$$\nr^\\pi_t(s)=\\sum_a\\pi_t(a\\mid s)\\,r(s,a),\\qquad P^\\pi_t(s,s')=\\sum_a\\pi_t(a\\mid s)\\,p(s'\\mid s,a)\n$$\n\n| $t$ | $r^\\pi_t(s_1)$ | $r^\\pi_t(s_2)$ | $P^\\pi_t$ |\n|---|---|---|---|\n| 0 | $0.7\\cdot5+0.3\\cdot10=6.5$ | $-1$ | $\\begin{bmatrix}0.35&0.65\\\\0&1\\end{bmatrix}$ |\n| 1 | $0.4\\cdot5+0.6\\cdot10=8$ | $-1$ | $\\begin{bmatrix}0.2&0.8\\\\0&1\\end{bmatrix}$ |\n\n$t=0$의 첫 행은 $P(s_1)=0.7\\cdot0.5+0.3\\cdot0=0.35$, $P(s_2)=0.7\\cdot0.5+0.3\\cdot1=0.65$이다.\n\n## Backward 계산\n\n정책 평가 재귀를 벡터로 쓰면 $v^\\pi_t=r^\\pi_t+P^\\pi_t v^\\pi_{t+1}$이다.\n\n- $t=2$: $v^\\pi_2=(0,0)$\n- $t=1$: $v^\\pi_1=r^\\pi_1=(8,\\,-1)$\n- $t=0$:\n$$\nv^\\pi_0(s_1)=6.5+0.35\\cdot8+0.65\\cdot(-1)=8.65,\\qquad v^\\pi_0(s_2)=-1+1\\cdot(-1)=-2\n$$\n\n같은 값을 행동별로 풀어 쓰면 확률적 정책 평가식이 그대로 확인된다.\n\n$$\nv^\\pi_0(s_1)=0.7\\underbrace{\\big(5+0.5\\cdot8+0.5\\cdot(-1)\\big)}_{8.5}+0.3\\underbrace{\\big(10+(-1)\\big)}_{9}=5.95+2.7=8.65\n$$\n\n**답:** $v^\\pi_0(s_1)=8.65$, $v^\\pi_0(s_2)=-2$.\n\n## 최적값과 비교\n\n같은 모델을 backward induction으로 풀면\n\n| $t$ | $Q^*_t(s_1,a_{11})$ | $Q^*_t(s_1,a_{12})$ | $v^*_t(s_1)$ | $\\pi^*_t(s_1)$ | $v^*_t(s_2)$ |\n|---|---|---|---|---|---|\n| 1 | 5 | 10 | 10 | $a_{12}$ | $-1$ |\n| 0 | $5+0.5\\cdot10+0.5\\cdot(-1)=9.5$ | $10-1=9$ | 9.5 | $a_{11}$ | $-2$ |\n\n이다. 확률적 정책의 값 8.65는 최적값 9.5보다 작다. 손실이 생기는 이유는 두 시점 모두에서 argmax가 아닌 행동에 확률을 주었기 때문이다.\n\n- $t=1$: $v^\\pi_1(s_1)=0.4\\cdot5+0.6\\cdot10=8<10$. 손실 $0.4\\cdot(10-5)=2$.\n- $t=0$: 행동 가치의 가중평균은 최댓값을 넘지 못한다.\n\n::: {.callout-tip}\n## 핵심\n확률적 정책의 값은 $Q$ 값들의 가중평균이므로 $\\max_a Q$를 넘을 수 없다. argmax 밖의 행동에 확률을 주면 그만큼 strictly 손해다. 이 모델에서 \"$t=0$에는 $a_{11}$, $t=1$에는 $a_{12}$\"인 결정론적 정책이 최적이고, 시점마다 최적 행동이 다르다.\n:::\n\n# 문제 4.6: 확률적 최단 경로 {#sec-p46}\n\n::: {.callout-note}\n## 문제\n아래 그래프에서 노드 1에서 노드 8로 가는 경로의 기대 총길이를 최소화하라. 호를 선택하면 그 호를 실제로 지나갈 확률은 다음과 같다.\n\n- 같은 노드에서 나가는 다른 호가 2개이면: 선택한 호 0.6, 다른 두 호 각각 0.2\n- 다른 호가 1개이면: 선택한 호 0.7, 다른 호 0.3\n- 다른 호가 없으면: 선택한 호 1\n\n호와 길이: $1\\to2:2$, $1\\to3:4$, $1\\to4:3$, $2\\to5:4$, $2\\to6:5$, $3\\to5:5$, $3\\to6:6$, $3\\to7:1$, $4\\to7:2$, $5\\to8:1$, $6\\to8:2$, $7\\to8:6$\n:::\n\n## MDP로 정식화\n\n| 요소 | 내용 |\n|---|---|\n| 시점 | $t=0$: 노드 1, $t=1$: 노드 2,3,4, $t=2$: 노드 5,6,7, $t=3$: 노드 8 ($T=3$) |\n| 상태 | 현재 노드 |\n| 행동 | 그 노드에서 나가는 호(목표로 하는 다음 노드) $a$ |\n| 전이확률 | $p(j\\mid i,a)$: 위 규칙 |\n| 비용 | 실제로 지나간 호의 길이 $c(i,j)$ |\n| 종단 비용 | $c_T(8)=0$ |\n\n비용이 다음 상태에 따라 달라지므로, 행동을 고를 시점의 기대 비용을 단계 비용으로 쓴다.\n\n$$\nc(i,a)=\\sum_j p(j\\mid i,a)\\,c(i,j)\n$$\n\nBellman 방정식은\n\n$$\nv_t(i)=\\min_a\\Big[c(i,a)+\\sum_j p(j\\mid i,a)\\,v_{t+1}(j)\\Big]=\\min_a\\sum_j p(j\\mid i,a)\\big(c(i,j)+v_{t+1}(j)\\big)\n$$\n\n이다. 각 호 $(i,j)$에 대해 $w(i,j):=c(i,j)+v(j)$를 먼저 계산하면 편하다.\n\n## Backward induction\n\n**$t=2$** (나가는 호가 하나뿐): $v(5)=1$, $v(6)=2$, $v(7)=6$\n\n**$t=1$**\n\n- 노드 4: 호 하나. $v(4)=2+v(7)=8$\n- 노드 2: $w(2,5)=4+1=5$, $w(2,6)=5+2=7$\n  - 5를 선택: $0.7\\cdot5+0.3\\cdot7=5.6$\n  - 6을 선택: $0.7\\cdot7+0.3\\cdot5=6.4$\n  - $v(2)=5.6$, 최적 행동 $2\\to5$\n- 노드 3: $w(3,5)=6$, $w(3,6)=8$, $w(3,7)=7$\n  - 5를 선택: $0.6\\cdot6+0.2\\cdot(8+7)=6.6$\n  - 6을 선택: $0.6\\cdot8+0.2\\cdot(6+7)=7.4$\n  - 7을 선택: $0.6\\cdot7+0.2\\cdot(6+8)=7.0$\n  - $v(3)=6.6$, 최적 행동 $3\\to5$\n\n**$t=0$** (노드 1): $w(1,2)=2+5.6=7.6$, $w(1,3)=4+6.6=10.6$, $w(1,4)=3+8=11$\n\n- 2를 선택: $0.6\\cdot7.6+0.2\\cdot(10.6+11)=8.88$\n- 3을 선택: $0.6\\cdot10.6+0.2\\cdot(7.6+11)=10.08$\n- 4를 선택: $0.6\\cdot11+0.2\\cdot(7.6+10.6)=10.24$\n- $v(1)=8.88$, 최적 행동 $1\\to2$\n\n**답:** 최적 기대 총길이 $8.88$. 최적 정책은 $1\\to2$, $2\\to5$, $3\\to5$, $4\\to7$, $5\\to8$, $6\\to8$, $7\\to8$를 시도하는 것이다.\n\n::: {.callout-tip}\n## 관찰\n- 결정론적 최단 경로 $1\\to2\\to5\\to8$의 길이는 7이다. 의도대로 가지 못할 위험이 기대 길이를 1.88 늘린다.\n- 최적 정책은 의도치 않게 도착한 노드 3, 4, 6, 7에서도 행동을 정해 준다. 정책을 상태 → 행동 규칙으로 최적화해야 하는 이유가 여기서 드러난다.\n- 노드 3에서 $3\\to7$은 첫 호가 1로 가장 짧지만 $w(3,7)=7$이라 최적이 아니다. 지금의 비용만이 아니라 이후 비용까지 본다는 Bellman 방정식의 의미 그대로다.\n:::\n\n::: {#bfa533dd .cell execution_count=1}\n``` {.python .cell-code}\narcs = {1: {2: 2, 3: 4, 4: 3}, 2: {5: 4, 6: 5}, 3: {5: 5, 6: 6, 7: 1},\n        4: {7: 2}, 5: {8: 1}, 6: {8: 2}, 7: {8: 6}}\n\ndef probs(node, chosen):\n    nb = list(arcs[node])\n    if len(nb) == 1:\n        return {chosen: 1.0}\n    if len(nb) == 2:\n        return {j: 0.7 if j == chosen else 0.3 for j in nb}\n    return {j: 0.6 if j == chosen else 0.2 for j in nb}\n\nv = {8: 0.0}\nfor node in [7, 6, 5, 4, 3, 2, 1]:          # 뒤에서부터\n    Q = {a: sum(p * (arcs[node][j] + v[j]) for j, p in probs(node, a).items())\n         for a in arcs[node]}\n    v[node] = min(Q.values())\n    best = min(Q, key=Q.get)\n    print(f\"node {node}: Q={ {a: round(q, 2) for a, q in Q.items()} } -> {node}->{best}, v={v[node]:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnode 7: Q={8: 6.0} -> 7->8, v=6.00\nnode 6: Q={8: 2.0} -> 6->8, v=2.00\nnode 5: Q={8: 1.0} -> 5->8, v=1.00\nnode 4: Q={7: 8.0} -> 4->7, v=8.00\nnode 3: Q={5: 6.6, 6: 7.4, 7: 7.0} -> 3->5, v=6.60\nnode 2: Q={5: 5.6, 6: 6.4} -> 2->5, v=5.60\nnode 1: Q={2: 8.88, 3: 10.08, 4: 10.24} -> 1->2, v=8.88\n```\n:::\n:::\n\n\n# 문제 4.21: 두 프로젝트 bandit {#sec-p421}\n\n::: {.callout-note}\n## 문제\n매 기간 두 프로젝트 중 하나를 고른다. 3기간 동안 기대 총보상을 최대화하라. 종단 보상은 0이다.\n\n- 프로젝트 1: 항상 상태 $s$, 고르면 보상 1\n- 프로젝트 2: 상태 $u$ 또는 $\\ell$\n  - $u$에서 고르면 보상 2, 다음 시점에 확률 0.5로 $\\ell$로 이동(나머지 0.5는 $u$ 유지)\n  - $\\ell$에서 고르면 보상 0, 다음 시점에 확률 1로 $u$로 이동\n- 고르지 않은 프로젝트는 상태가 변하지 않는다.\n:::\n\n원 문제에서 프로젝트 2의 두 번째 상태 이름은 $t$인데, 시점 첨자 $t$와 겹치므로 여기서는 $\\ell$로 바꿔 썼다. 3기간은 결정 시점 $t=0,1,2$, $T=3$으로 해석했다.\n\n## 정식화\n\n프로젝트 1은 상태가 변하지 않으므로 MDP의 상태는 프로젝트 2의 상태 $x\\in\\{u,\\ell\\}$이다. 행동은 $a\\in\\{1,2\\}$(고르는 프로젝트).\n\n$$\n\\begin{aligned}\nQ_t(x,1)&=1+v_{t+1}(x)\\quad(\\text{프로젝트 2는 그대로})\\\\\nQ_t(u,2)&=2+0.5\\,v_{t+1}(\\ell)+0.5\\,v_{t+1}(u)\\\\\nQ_t(\\ell,2)&=0+v_{t+1}(u)\n\\end{aligned}\n$$\n\n## Backward induction\n\n| $t$ | $Q_t(u,1)$ | $Q_t(u,2)$ | $v_t(u)$ | $Q_t(\\ell,1)$ | $Q_t(\\ell,2)$ | $v_t(\\ell)$ |\n|---|---|---|---|---|---|---|\n| 3 | – | – | 0 | – | – | 0 |\n| 2 | 1 | **2** | 2 | **1** | 0 | 1 |\n| 1 | 3 | **3.5** | 3.5 | **2** | **2** | 2 |\n| 0 | 4.5 | **4.75** | 4.75 | 3 | **3.5** | 3.5 |\n\n계산 예 ($t=0$): $Q_0(u,2)=2+0.5\\cdot2+0.5\\cdot3.5=4.75$, $Q_0(\\ell,2)=0+3.5=3.5$.\n\n**답:** 최적 기대 총보상은 프로젝트 2가 $u$에서 시작하면 4.75, $\\ell$에서 시작하면 3.5이다. 최적 정책은\n\n| $t$ | $x=u$ | $x=\\ell$ |\n|---|---|---|\n| 0 | 프로젝트 2 | 프로젝트 2 |\n| 1 | 프로젝트 2 | 프로젝트 1 또는 2 (동점) |\n| 2 | 프로젝트 2 | 프로젝트 1 |\n\n::: {.callout-tip}\n## 관찰\n- **시점마다 결정 규칙이 다르다.** $\\ell$에서 프로젝트 2를 고르면 지금은 0이지만 다음에 $u$가 되어 보상 2를 얻을 기회가 생긴다. 남은 시간이 충분한 $t=0$에서는 이 투자가 이득이고, 마지막 $t=2$에서는 회수할 시간이 없으므로 프로젝트 1이 낫다.\n- **동점이 있으면 최적 정책이 여러 개다.** $t=1$, $x=\\ell$에서 두 행동의 값이 모두 2이므로 결정론적 최적 정책은 2개이고, 두 행동을 임의의 비율로 섞은 확률적 정책도 모두 최적이다. 최적 가치함수는 하나뿐이다.\n:::\n\n::: {#11085b13 .cell execution_count=2}\n``` {.python .cell-code}\nv = {\"u\": 0.0, \"l\": 0.0}                       # v_3\nfor t in [2, 1, 0]:\n    Q = {(\"u\", 1): 1 + v[\"u\"], (\"u\", 2): 2 + 0.5 * v[\"l\"] + 0.5 * v[\"u\"],\n         (\"l\", 1): 1 + v[\"l\"], (\"l\", 2): 0 + v[\"u\"]}\n    v = {x: max(Q[(x, 1)], Q[(x, 2)]) for x in [\"u\", \"l\"]}\n    print(f\"t={t}: Q={Q}  v={v}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt=2: Q={('u', 1): 1.0, ('u', 2): 2.0, ('l', 1): 1.0, ('l', 2): 0.0}  v={'u': 2.0, 'l': 1.0}\nt=1: Q={('u', 1): 3.0, ('u', 2): 3.5, ('l', 1): 2.0, ('l', 2): 2.0}  v={'u': 3.5, 'l': 2.0}\nt=0: Q={('u', 1): 4.5, ('u', 2): 4.75, ('l', 1): 3.0, ('l', 2): 3.5}  v={'u': 4.75, 'l': 3.5}\n```\n:::\n:::\n\n\n# 문제 4.25: Bellman 방정식의 증명 (ε 논법) {#sec-p425}\n\n::: {.callout-note}\n## 문제\n$v^*_t(h_t):=\\sup_{\\pi}v^\\pi_t(h_t)$가 최적성 방정식\n$$\nv^*_t(h_t)=\\sup_{a\\in A_{s_t}}\\Big\\{r_t(s_t,a)+\\sum_{j\\in S}p_t(j\\mid s_t,a)\\,v^*_{t+1}(h_t,a,j)\\Big\\},\\qquad v^*_T(h_T)=r_T(s_T)\n$$\n를 만족함을 다음 순서로 보여라. (a) $\\ge$ 방향, (b) $\\le$ 방향, (c) 결합.\n\n여기서 $h_t=(s_0,a_0,\\dots,s_t)$는 시점 $t$까지의 history이고, 정책은 history에 의존하는 확률적 정책까지 허용한다.\n:::\n\n**가정.** $S$는 유한 또는 가산, $|r_t|\\le M<\\infty$. 따라서 모든 $v^\\pi_t$와 $v^*_t$는 유한하다.\n\n::: {.callout-important}\n## 이 증명이 앞의 증명과 다른 점\n최적 정책이 존재한다고 가정하면 $(\\ge)$ 방향에서 \"이후 결정 규칙을 최적인 것으로 바꾼다\"는 한 줄로 끝난다. 이 문제는 그 가정 없이, sup의 정의로 얻는 **ε-최적 정책**만으로 같은 결론을 낸다. 대가로 이후 정책이 다음 상태에 따라 달라져야 하므로 history 의존 정책이 필요하다.\n:::\n\n**종단 조건.** 시점 $T$에는 행동이 없으므로 모든 정책에서 $v^\\pi_T(h_T)=r_T(s_T)$이고, 따라서 $v^*_T(h_T)=r_T(s_T)$이다.\n\n## (a) $\\ge$ 방향\n\n$\\epsilon>0$과 행동 $a\\in A_{s_t}$를 임의로 고정한다.\n\n1. sup의 정의에 의해, 각 $j\\in S$에 대해 시점 $t+1$부터의 정책 $\\pi^{j}$가 존재하여\n$$\nv^{\\pi^{j}}_{t+1}(h_t,a,j)\\ \\ge\\ v^*_{t+1}(h_t,a,j)-\\epsilon.\n$$\n2. 정책 $\\pi'$을 다음과 같이 만든다. 시점 $t$에는 $a$를 확정적으로 고르고, 시점 $t+1$에 상태 $j$에 도착하면 그 후로 $\\pi^{j}$를 따른다. 이후 행동이 $j$에 의존하므로 $\\pi'$은 history 의존 정책이고, 허용된 정책 집합에 속한다.\n3. 정책 평가 재귀에 의해\n$$\nv^{\\pi'}_t(h_t)=r_t(s_t,a)+\\sum_j p_t(j\\mid s_t,a)\\,v^{\\pi^{j}}_{t+1}(h_t,a,j)\\ \\ge\\ r_t(s_t,a)+\\sum_j p_t(j\\mid s_t,a)\\,v^*_{t+1}(h_t,a,j)-\\epsilon.\n$$\n   마지막 부등식은 1과 $\\sum_j p_t(j\\mid s_t,a)=1$에서 나온다.\n4. $v^*_t(h_t)\\ge v^{\\pi'}_t(h_t)$이므로\n$$\nv^*_t(h_t)\\ \\ge\\ r_t(s_t,a)+\\sum_j p_t(j\\mid s_t,a)\\,v^*_{t+1}(h_t,a,j)-\\epsilon.\n$$\n5. $a$와 $\\epsilon$이 임의이므로 $a$에 대해 sup을 취하고 $\\epsilon\\to0$으로 보내면\n$$\nv^*_t(h_t)\\ \\ge\\ \\sup_{a\\in A_{s_t}}\\Big\\{r_t(s_t,a)+\\sum_j p_t(j\\mid s_t,a)\\,v^*_{t+1}(h_t,a,j)\\Big\\}.\n$$\n\n## (b) $\\le$ 방향\n\n$\\epsilon>0$을 고정한다.\n\n1. sup의 정의에 의해 정책 $\\pi'$가 존재하여 $v^{\\pi'}_t(h_t)\\ge v^*_t(h_t)-\\epsilon$.\n2. $\\pi'$이 시점 $t$에 history $h_t$에서 행동 분포 $q(\\cdot)$를 쓴다고 하자. 정책 평가 재귀에 의해\n$$\nv^{\\pi'}_t(h_t)=\\sum_a q(a)\\Big[r_t(s_t,a)+\\sum_j p_t(j\\mid s_t,a)\\,v^{\\pi'}_{t+1}(h_t,a,j)\\Big].\n$$\n3. $v^{\\pi'}_{t+1}\\le v^*_{t+1}$이고 가중치 $q(a)p_t(j\\mid s_t,a)$는 음이 아니므로\n$$\nv^{\\pi'}_t(h_t)\\ \\le\\ \\sum_a q(a)\\,w(a),\\qquad w(a):=r_t(s_t,a)+\\sum_j p_t(j\\mid s_t,a)\\,v^*_{t+1}(h_t,a,j).\n$$\n4. 확률분포에 대한 가중평균은 상한을 넘지 못한다: $\\sum_a q(a)w(a)\\le\\sup_a w(a)$.\n5. 1~4를 합치면 $v^*_t(h_t)-\\epsilon\\le\\sup_a w(a)$이고, $\\epsilon\\to0$으로 보내면\n$$\nv^*_t(h_t)\\ \\le\\ \\sup_{a\\in A_{s_t}}\\Big\\{r_t(s_t,a)+\\sum_j p_t(j\\mid s_t,a)\\,v^*_{t+1}(h_t,a,j)\\Big\\}.\n$$\n\n## (c) 결합\n\n(a)와 (b)로 등호가 성립하고, 종단 조건과 함께 $v^*_t$는 최적성 방정식을 만족한다. $\\blacksquare$\n\n::: {.callout-tip}\n## 짚어 둘 점\n- 이 증명에는 귀납법이 필요 없다. 각 $t$에서 정의(sup)와 정책 평가 재귀만 썼다.\n- $(\\ge)$ 방향의 핵심은 2단계의 **이어 붙이기**다. 다음 상태마다 다른 ε-최적 정책을 붙이므로 history 의존 정책이 필요하다. 이렇게 얻은 결과에 역방향 귀납을 적용하면 $v^*_t(h_t)$가 $s_t$에만 의존함을 보일 수 있고, 그 다음에야 Markov 정책으로 충분하다는 결론이 나온다.\n- 유한 $S$, $A$이면 sup이 max가 되어 최적 정책이 존재하므로, ε 없이 $(\\ge)$ 방향을 바로 쓸 수 있다.\n:::\n\n# 문제 4.30, 4.31: 옵션 행사 시점 {#sec-p430}\n\n::: {.callout-note}\n## 문제\n- **4.30 (콜)** 현재 주가 30달러. 하루 주가 변화는 $+0.10$ (확률 0.6), $0$ (0.1), $-0.10$ (0.3). 앞으로 30일 안에 언제든 100주를 주당 31달러에 살 수 있는 옵션의 가치와 최적 행사 정책을 구하라. 행사 시 거래비용 50달러.\n- **4.31 (풋)** 같은 주가에서 하루 변화가 $+0.10$ (0.4), $0$ (0.1), $-0.10$ (0.5). 30일 안에 100주를 주당 29달러에 팔 수 있는 옵션.\n- 각각 화폐의 시간 가치와 주가 변화 분포가 결과에 주는 영향을 조사하라.\n:::\n\n## 최적 정지 문제를 MDP로\n\n| 요소 | 내용 |\n|---|---|\n| 시점 | $t=0$(오늘), $1,\\dots,30$. 매일 행사 여부를 결정할 수 있다고 해석 |\n| 상태 | 주가 $S_t\\in\\{30+0.1k\\}$, 그리고 이미 행사한 뒤의 흡수 상태 $\\Delta$ |\n| 행동 | 행사(stop) 또는 대기(continue) |\n| 보상 | 행사하면 $g(S)$를 받고 $\\Delta$로 이동. 대기하면 0 |\n| 종단 보상 | $r_{30}(S)=\\max\\{g(S),0\\}$ (마지막 날 이익이면 행사) |\n\n행사 수익은 콜이 $g(S)=100(S-31)-50$, 풋이 $g(S)=100(29-S)-50$이다. 일일 할인인자를 $\\beta=1/(1+r/365)$로 두면 ($r$: 연이자율) Bellman 방정식은\n\n$$\nv_t(S)=\\max\\Big\\{\\,g(S),\\ \\ \\beta\\big[p_+v_{t+1}(S+0.1)+p_0v_{t+1}(S)+p_-v_{t+1}(S-0.1)\\big]\\Big\\},\\qquad v_{30}(S)=\\max\\{g(S),0\\}\n$$\n\n이다. 할인을 넣는 것은 $r_t=\\beta^t r$로 보상에 넣는 것과 같다. 행사 이익이 음수이면 행사하지 않으면 되므로 첫 항을 $\\max\\{g,0\\}$로 써도 결과가 같다. 30일 동안 주가는 최대 $\\pm3$달러만 움직이므로 상태는 61개면 충분하다.\n\n## 결과\n\n::: {#2d099713 .cell execution_count=3}\n``` {.python .cell-code}\nimport numpy as np\n\ndef option(kind, pu, p0, pd, K, S0=30.0, n=100, cost=50.0, days=30, beta=1.0, tick=0.10):\n    ks = np.arange(-days, days + 1)\n    S = S0 + tick * ks\n    g = n * (S - K) - cost if kind == \"call\" else n * (K - S) - cost\n    v = np.maximum(g, 0.0)                         # v_30\n    early = []\n    for t in range(days - 1, -1, -1):              # t = 29, ..., 0\n        cont = np.zeros_like(v)\n        cont[1:-1] = beta * (pu * v[2:] + p0 * v[1:-1] + pd * v[:-2])\n        stop = (g >= cont) & (g > 0)\n        if (stop & (np.abs(ks) <= t)).any():       # 시점 t에 도달 가능한 주가에서 조기 행사?\n            early.append(t)\n        v = np.where(stop, g, cont)\n    return v[days], early\n\nbase = {\"call\": (31.0, (0.6, 0.1, 0.3)), \"put\": (29.0, (0.4, 0.1, 0.5))}\nfor kind, (K, d) in base.items():\n    print(f\"== {kind}, K={K}, (p+,p0,p-)={d}\")\n    for r in [0.0, 0.05, 0.20]:\n        val, early = option(kind, *d, K, beta=1 / (1 + r / 365))\n        print(f\"  연이자율 {r:.2f}: 가치 {val:6.2f}, 조기 행사 시점 {early}\")\n    for d2 in [(0.3, 0.1, 0.6), (0.45, 0.1, 0.45), (0.6, 0.1, 0.3), (0.5, 0.0, 0.5)]:\n        val, _ = option(kind, *d2, K)\n        print(f\"  분포 {d2}: 가치 {val:6.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n== call, K=31.0, (p+,p0,p-)=(0.6, 0.1, 0.3)\n  연이자율 0.00: 가치   2.40, 조기 행사 시점 []\n  연이자율 0.05: 가치   2.39, 조기 행사 시점 []\n  연이자율 0.20: 가치   2.36, 조기 행사 시점 []\n  분포 (0.3, 0.1, 0.6): 가치   0.00\n  분포 (0.45, 0.1, 0.45): 가치   0.02\n  분포 (0.6, 0.1, 0.3): 가치   2.40\n  분포 (0.5, 0.0, 0.5): 가치   0.04\n== put, K=29.0, (p+,p0,p-)=(0.4, 0.1, 0.5)\n  연이자율 0.00: 가치   0.14, 조기 행사 시점 []\n  연이자율 0.05: 가치   0.14, 조기 행사 시점 []\n  연이자율 0.20: 가치   0.14, 조기 행사 시점 []\n  분포 (0.3, 0.1, 0.6): 가치   2.40\n  분포 (0.45, 0.1, 0.45): 가치   0.02\n  분포 (0.6, 0.1, 0.3): 가치   0.00\n  분포 (0.5, 0.0, 0.5): 가치   0.04\n```\n:::\n:::\n\n\n| | 콜 (4.30) | 풋 (4.31) |\n|---|---|---|\n| 옵션 가치 ($r=0$) | 약 2.40달러 | 약 0.14달러 |\n| $r=5\\%$, $20\\%$ | 2.39, 2.36 | 0.14, 0.14 |\n| 최적 정책 | 만기 전에는 행사하지 않고, 마지막 날 $S_{30}\\ge31.6$이면 행사 | 만기 전에는 행사하지 않고, 마지막 날 $S_{30}\\le28.4$이면 행사 |\n\n마지막 날 행사 조건은 $g(S)>0$에서 나온다. 콜은 $100(S-31)>50$, 즉 $S>31.5$인데 주가가 0.1 단위이므로 $S\\ge31.6$이다. 풋도 같은 방식이다.\n\n| 분포 $(p_+,p_0,p_-)$ | 콜 가치 | 풋 가치 |\n|---|---|---|\n| (0.3, 0.1, 0.6) | 0.00 | 2.40 |\n| (0.45, 0.1, 0.45) | 0.02 | 0.02 |\n| (0.6, 0.1, 0.3) | 2.40 | 0.00 |\n| (0.5, 0.0, 0.5) | 0.04 | 0.04 |\n\n## 해석\n\n**조기 행사를 하지 않는 이유.** 콜에서 하루 기대 주가 변화는 $\\mu=0.1(0.6-0.3)=0.03>0$이다. $v_{t+1}\\ge g$이므로 $\\beta=1$일 때\n\n$$\n\\mathbb{E}[v_{t+1}(S')]\\ \\ge\\ \\mathbb{E}[g(S')]=g(S)+100\\mu\\ >\\ g(S)\n$$\n\n이다. 즉 대기의 가치가 항상 즉시 행사보다 크므로 행사를 미룬다. 할인이 있으면 대기 가치가 $\\beta\\big(g(S)+100\\mu\\big)$ 이상이므로, 조기 행사가 나으려면 $g(S)>\\frac{100\\beta\\mu}{1-\\beta}$여야 한다. 연 5%이면 우변이 약 2만 달러인데 30일 안에 $g$는 최대 150달러이므로 조기 행사는 일어나지 않는다. 풋도 $\\mu=-0.01$로 주가가 내려가는 쪽이므로 같은 논리다.\n\n**화폐의 시간 가치.** 이자율을 높이면 미래에 받을 행사 이익을 덜 쳐주므로 가치가 조금 줄지만, 30일이라는 짧은 기간에서는 효과가 작다.\n\n**주가 분포.** 결과를 좌우하는 것은 분포다. 행사 수익을 내려면 콜은 주가가 1.6달러, 풋은 1.6달러 움직여야 하는데, 하루 변동이 0.1달러뿐이라 유리한 쪽으로의 추세(drift)가 없으면 30일 안에 도달할 확률이 매우 작다. 추세가 유리할수록 가치가 크게 오른다. 추세가 불리하거나 없으면 거래비용 50달러 때문에 가치가 거의 0이다.\n\n::: {.callout-tip}\n## 최적 정지 문제의 구조\n최적 정지 문제는 \"멈춤\"이라는 행동과 흡수 상태 $\\Delta$를 가진 유한 구간 MDP다. Bellman 방정식이 \"지금 멈춘 값\"과 \"기다린 값의 기댓값\" 중 큰 쪽을 고르는 형태가 되어, 지금의 이득과 미래 이득의 균형이라는 의미가 가장 직접적으로 드러난다.\n:::\n\n# 문제별 핵심 개념 정리 {#sec-summary}\n\n| 문제 | 연습한 것 |\n|---|---|\n| 4.1 | 확률적 정책 → 정책 보상 벡터와 전이 행렬, backward 정책 평가, 확률적 정책이 최적보다 못한 이유 |\n| 4.6 | 최소화 Bellman 방정식, 비용이 다음 상태에 의존할 때 기대 단계 비용으로 바꾸기, 의도치 않은 상태에서의 정책 |\n| 4.21 | 시점마다 다른 최적 결정 규칙, 동점과 복수의 최적 정책 |\n| 4.25 | 최적 정책 존재 가정 없이 Bellman 방정식 증명: ε-최적 정책과 이어 붙이기 |\n| 4.30, 4.31 | 최적 정지를 MDP로 정식화, 코드로 backward induction, 구조적 성질(조기 행사 없음)을 Bellman 방정식으로 증명 |\n\n",
    "supporting": [
      "e2-finite-horizon-mdp-exercises_files"
    ],
    "filters": [],
    "includes": {}
  }
}