#include <stdio.h>
#include <chrono>
#include <iostream>
#include <random>

using namespace std;
using namespace std::chrono;
using std::chrono::system_clock;

bool check_sorted(int* arr, int n) {
    for (size_t i = 1; i < n; i++) {
        if (arr[i - 1] > arr[i]) {
            return false;
        }
    }
    return true;
}

void print_arr(int* arr, int n) {
    for (size_t i = 0; i < n; i++) {
        if (i) cout << ", ";
        cout << arr[i];
    }
    cout << endl;
}

int* gen_data(int n, int seed = 0) {
    int* arr = new int[n];
    mt19937 rs(seed);
    uniform_int_distribution<int> dist(0, INT32_MAX);

    for (size_t i = 0; i < n; i++) {
        arr[i] = dist(rs);
    }
    return arr;
}

// copy this template and implement your algorihtm
int* mysort(int* arr, int n) {
    int* sorted = new int[n];
    for (size_t i = 0; i < n; i++) {
        sorted[i] = arr[i];
    }
    // implement your algorithm

    return sorted;
}
int* insertion_sort(int* arr, int n) {
    int* sorted = new int[n];
    for (size_t i = 0; i < n; i++) {
        sorted[i] = arr[i];
    }

    // implement your algorithm
    for(int j = 1; j < n; j++) {
        int key = sorted[j];
        int i = j - 1;
        while(i >= 0 && sorted[i] > key) {
            sorted[i + 1] = sorted[i];
            i = i - 1;
        }
        sorted[i + 1] = key;
    }
    return sorted;
}
int* merge_sort(int* arr, int n) {
    int* sorted = new int[n];
    for (size_t i = 0; i < n; i++) {
        sorted[i] = arr[i];
    }

    // implement your algorithm
    auto _merge = [](int* A, int p, int q, int r) -> void {
        int n1 = q - p + 1;
        int n2 = r - q;

        // INT32_MAX can be assigned to A since the input is generated by gen_data, which generates numbers in the range [0, INT32_MAX]
        // We assign unsigned int to L, R to allocate sentinel value as UINT32_MAX, which is greater than any value in A
        auto L = new unsigned int[n1 + 1];
        auto R = new unsigned int[n2 + 1];

        // from p to q, copy to L
        for(int i = 0; i < n1; i++) {
            L[i] = A[p + i];
        }

        // from q + 1 to r, copy to R
        for(int j = 0; j < n2; j++) {
            R[j] = A[q + 1 + j];
        }

        L[n1] = UINT32_MAX;
        R[n2] = UINT32_MAX;

        int i = 0, j = 0;
        for(int k = p; k <= r; k++) {
            if(L[i] <= R[j]) {
                A[k] = L[i];
                i++;
            } else {
                A[k] = R[j];
                j++;
            }
        }

        delete[] L;
        delete[] R;
    };

    auto _merge_sort = [&](auto&& self, int* A, int p, int r) -> void{
        if (p < r) {
            int q = (p + r) / 2;
            self(self, A, p, q);
            self(self, A, q + 1, r);
            _merge(A, p, q, r);
        }
    };
    _merge_sort(_merge_sort, sorted, 0, n - 1);
    return sorted;
}
int* quick_sort_rand_piv(int* arr, int n) {
    int* sorted = new int[n];
    for (size_t i = 0; i < n; i++) {
        sorted[i] = arr[i];
    }

    // implement your algorithm
    auto _partition_rand_piv = [](int* A, int p, int r) -> int {
        // pivot as the last element
        int x = A[r];
        int i = p - 1;
        for(int j = p; j < r; j++) {
            if(A[j] <= x) {
                i++;
                swap(A[i], A[j]);
            }
        }
        swap(A[i + 1], A[r]);
        return i + 1;
    };

    // use a fixed seed to make the result deterministic
    mt19937 rs(260331);

    auto _quick_sort_rand_piv = [&](auto&& self, int* A, int p, int r) -> void {
        if (p < r) {
            uniform_int_distribution<int> dist(p, r);
            int rand_piv_idx = dist(rs);
            swap(A[rand_piv_idx], A[r]);

            int q = _partition_rand_piv(A, p, r);
            self(self, A, p, q - 1);
            self(self, A, q + 1, r);
        }
    };
    _quick_sort_rand_piv(_quick_sort_rand_piv, sorted, 0, n - 1);
    return sorted;
}
int* quick_sort_last_piv(int* arr, int n) {
    int* sorted = new int[n];
    for (size_t i = 0; i < n; i++) {
        sorted[i] = arr[i];
    }

    // implement your algorithm
    auto _partition = [](int* A, int p, int r) -> int {
        // pivot as the last element
        int x = A[r];
        int i = p - 1;
        for(int j = p; j < r; j++) {
            if(A[j] <= x) {
                i++;
                swap(A[i], A[j]);
            }
        }
        swap(A[i + 1], A[r]);
        return i + 1;
    };

    auto _quick_sort = [&](auto&& self, int* A, int p, int r) -> void {
        if (p < r) {
            int q = _partition(A, p, r);
            self(self, A, p, q - 1);
            self(self, A, q + 1, r);
        }
    };
    _quick_sort(_quick_sort, sorted, 0, n - 1);
    return sorted;
}
int* heap_sort(int* arr, int n) {
    int* sorted = new int[n];
    for (size_t i = 0; i < n; i++) {
        sorted[i] = arr[i];
    }

    // implement your algorithm
    struct Heap {
        int* A;
        int heap_size;

        Heap() : A(nullptr), heap_size(0) {}
    };

    auto _max_heapify = [&](auto&& self, Heap* A, int i) -> void {
        int largest = i;
        int l = 2 * i + 1;
        int r = 2 * i + 2;

        if (l < A->heap_size && A->A[l] > A->A[largest]) {
            largest = l;
        }
        if (r < A->heap_size && A->A[r] > A->A[largest]) {
            largest = r;
        }
        if (largest != i) {
            swap(A->A[i], A->A[largest]);
            self(self, A, largest);
        }
    };

    auto _build_max_heap = [&](Heap* heap, int n) -> void {
        heap->A = sorted;
        heap->heap_size = n;

        // zero-based index, so the last non-leaf node is n / 2 - 1
        for(int i = n / 2 - 1; i >= 0; i--) {
            _max_heapify(_max_heapify, heap, i);
        }
    };

    Heap heap;
    _build_max_heap(&heap, n);

    for(int i = n - 1; i > 0; i--) {
        swap(sorted[0], sorted[i]);
        heap.heap_size = heap.heap_size - 1;
        _max_heapify(_max_heapify, &heap, 0);
    }

    return sorted;
}
int* radix_sort(int* arr, int n) {
    int* sorted = new int[n];
    for (size_t i = 0; i < n; i++) {
        sorted[i] = arr[i];
    }

    // implement your algorithm
    auto _counting_sort = [](int* A, int n, long long exp) -> void {
        int* output = new int[n];
        int count[10] = {0};

        for(int i = 0; i < n; i++) {
            count[(A[i] / exp) % 10]++;
        }
        for(int i = 1; i < 10; i++) {
            count[i] += count[i - 1];
        }
        for(int i = n - 1; i >= 0; i--) {
            output[count[(A[i] / exp) % 10] - 1] = A[i];
            count[(A[i] / exp) % 10]--;
        }
        for(int i = 0; i < n; i++) {
            A[i] = output[i];
        }
        delete[] output;
    };

    // find the maximum number to know the number of digits
    int max_num = sorted[0];
    for(int i = 1; i < n; i++) {
        if (sorted[i] > max_num) {
            max_num = sorted[i];
        }
    }

    // do counting sort for every digit
    // exp is defined as long long to avoid overflow when exp is greater than 10^9
    for(long long exp = 1; max_num / exp > 0; exp *= 10) {
        _counting_sort(sorted, n, exp);
    }

    return sorted;
}

int main(void) {
    freopen("hw2_sort.log", "w", stdout);
    system_clock::time_point begin;
    double duration;
    bool is_sorted;
    int* arr;
    int n;

    // example of gen_data
    arr = gen_data(10);
    cout << "Example: ";
    print_arr(arr, 10);
    delete[] arr;

    int* (*sort_func[])(int*, int) = {insertion_sort, merge_sort, quick_sort_rand_piv, quick_sort_last_piv, heap_sort, radix_sort};
    const char* sort_func_names[] = {"Insertion Sort", "Merge Sort", "Quick Sort (Random Pivot)", "Quick Sort (Last Pivot)", "Heap Sort", "Radix Sort"};

    for(int i = 0; i < 6; i++) {
        for(int n = 100; n <= 100000000; n *= 10) {
            for(int seed = 0; seed < 5; seed++) {
                arr = gen_data(n, seed);
                begin = system_clock::now();
                int* sorted = sort_func[i](arr, n);
                duration = duration_cast<milliseconds>(system_clock::now() - begin).count() / 1000.0;

                printf("%d. %-40s (n = %-10d, seed = %d)  Time for sort: %3.6fs\n", i + 1, sort_func_names[i], n, seed, duration);

                is_sorted = check_sorted(sorted, n);
                if (!is_sorted) {
                    cout << "Try the implementation again" << endl;
                }
                delete[] sorted;
                delete[] arr;
            }
            printf("-----------------------------------------\n");
        }
    }
    return 0;
}